# Generated by Django 3.1.7 on 2021-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('cbhs_code', models.CharField(max_length=255)),
                ('date_received', models.DateTimeField()),
                ('received_from', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('worksheet_printed', models.BooleanField()),
                ('cpu_model', models.CharField(max_length=255)),
                ('cpu_speed', models.CharField(max_length=255)),
                ('ram_in_gigabytes', models.IntegerField()),
                ('storage', models.CharField(max_length=255)),
                ('drive_capacity', models.IntegerField()),
                ('does_it_boot', models.BooleanField()),
                ('os_installed', models.CharField(max_length=255)),
                ('battery_tested', models.IntegerField()),
                ('hdd_ssd_chkdsk', models.BooleanField()),
                ('cpu_temps', models.IntegerField()),
                ('keyboard', models.BooleanField()),
                ('trackpad', models.BooleanField()),
                ('usb', models.BooleanField()),
                ('display_out', models.BooleanField()),
                ('actions_required', models.TextField()),
                ('date_last_worked_on', models.DateTimeField()),
                ('notes', models.TextField()),
                ('worked_on_by', models.CharField(max_length=255)),
                ('signed_off_by', models.CharField(max_length=255)),
                ('sent_to', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['-cbhs_code'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
