# Generated by Django 3.1.7 on 2021-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210607_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='cbhs_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_speed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='date_received',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram_in_gigabytes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='received_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='worksheet_printed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
