# Generated by Django 3.1.7 on 2021-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210607_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='battery_tested',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_temps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='display_out',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='does_it_boot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='drive_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='hdd_ssd_chkdsk',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='keyboard',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os_installed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='trackpad',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='usb',
            field=models.BooleanField(null=True),
        ),
    ]
