# Generated by Django 3.1.7 on 2021-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210607_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='actions_required',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='date_last_worked_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='sent_to',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='signed_off_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='worked_on_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
