# Generated by Django 3.1.7 on 2021-06-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210607_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-cbhs_code']},
        ),
    ]
