# Generated by Django 3.1.7 on 2021-08-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210607_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, null=True)),
                ('resolution', models.CharField(max_length=255, null=True)),
                ('processor', models.CharField(max_length=255, null=True)),
                ('processor_speed', models.CharField(max_length=255, null=True)),
                ('connectivity', models.CharField(max_length=255, null=True)),
                ('RAM', models.CharField(max_length=255, null=True)),
                ('storage', models.IntegerField(max_length=255, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['-model_name'],
            },
        ),
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='actions_required',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cpu_speed',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='drive_capacity',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='make',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram_in_gigabytes',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='worksheet_printed',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting for Parts', 'Waiting for Parts'), ('Complete', 'Complete')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.laptop_model'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os_installed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.operating_system'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.provider'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.receiver'),
        ),
    ]
