# Generated by Django 3.1.7 on 2021-08-12 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20210812_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='slug',
        ),
        migrations.AddField(
            model_name='laptop',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laptop_model',
            name='storage',
            field=models.IntegerField(null=True),
        ),
    ]
