# Generated by Django 3.1.7 on 2021-08-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210812_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='author',
            new_name='technician',
        ),
    ]
