# Generated by Django 3.1.7 on 2021-08-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210812_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='password_expires',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='windows_activated',
            field=models.BooleanField(null=True),
        ),
    ]
