# Generated by Django 3.1.7 on 2021-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210814_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery_tested',
            field=models.BooleanField(null=True),
        ),
    ]
