# Generated by Django 3.1.7 on 2021-08-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210814_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='worked_on_by',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='signed_off_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
