# Generated by Django 3.1.7 on 2021-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210814_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cpu_temps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
