# Generated by Django 3.1.7 on 2021-09-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210907_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cbhs_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
