# Generated by Django 3.1.7 on 2021-09-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210918_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='battery_tested',
            new_name='optimisation_script',
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery_wear_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.laptop_model'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='os_installed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.operating_system'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.provider'),
        ),
    ]
